require 'aop-client/resource/category_postcat_get'
require 'aop-client/resource/category_attr_get'
require 'aop-client/resource/category_attrvalue_get'
require 'aop-client/resource/photobank_list'
require 'aop-client/resource/photobank_upload'