require 'aop-client/response/base'
require 'aop-client/response/category_postcat_get'
require 'aop-client/response/category_attr_get'
require 'aop-client/response/category_attrvalue_get'
require 'aop-client/response/photobank_list'
require 'aop-client/response/photobank_upload'
require 'aop-client/response/open_product_post'
require 'aop-client/response/oauth'
